### ISSUE TITLE
Selection of multiple sites

### ISSUE THREAD

**Issue by davidwang20** [jbloomlab/SARS2_RBD_Ab_escape_maps#1]
In the video demo I see that you are able to select multiple sites. However I can't seem to do this on the actual site: https://jbloomlab.github.io/SARS2_RBD_Ab_escape_maps/escape-calc/

Is there a keyboard shortcut I'm missing?

**Comment by jbloom** [comment]
Shift-click should do it. Does that not work?

**Comment by davidwang20** [comment]
It works, I didn't read. Thanks!
