### ISSUE TITLE
AxLimSetter TypeError

### ISSUE THREAD

**Issue by ryancorn** [jbloomlab/SARS2_RBD_Ab_escape_maps#2]
Hi, 

I am trying to locally run the python version and I am receiving the following error upon running python process_data.py

![image](https://user-images.githubusercontent.com/64803810/152835170-fa4581d4-90a7-4521-888b-776d3e4e76af.png)

**Comment by jbloom** [comment]
Does upgrading `dmslogo` to 0.6.3 fix this?

**Comment by ryancorn** [comment]
Yep, works fine now.
